/**
 * Recruiter Task Entity
 * 
 * Manages recruitment to-dos, screening checklists, interview follow-ups,
 * and automated pipeline action items.
 */

const mongoose = require('mongoose');

const taskSchema = new mongoose.Schema({
  title: {
    type: String,
    required: true,
    trim: true,
  },
  description: {
    type: String,
    trim: true,
    default: '',
  },
  priority: {
    type: String,
    enum: ['URGENT', 'HIGH', 'MEDIUM', 'LOW'],
    default: 'MEDIUM',
  },
  category: {
    type: String,
    enum: ['CANDIDATE_REVIEW', 'INTERVIEW_PREP', 'OFFER_MANAGEMENT', 'SOURCING', 'TEAM_SYNC', 'GENERAL'],
    default: 'GENERAL',
  },
  dueDate: {
    type: Date,
    default: null,
  },
  status: {
    type: String,
    enum: ['PENDING', 'IN_PROGRESS', 'COMPLETED'],
    default: 'PENDING',
  },
  completedAt: {
    type: Date,
    default: null,
  },
  relatedJob: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'Job',
    default: null,
  },
  relatedCandidate: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'Application',
    default: null,
  },
  createdBy: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'User',
    required: true,
  },
  companyId: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'Company',
    default: null,
  },
  isAutoGenerated: {
    type: Boolean,
    default: false,
  }
}, { timestamps: true });

module.exports = mongoose.model('Task', taskSchema);
