import React, { useState } from 'react';
import axios from 'axios';
import { ArrowLeft, ArrowRight, Check, Plus, Trash2 } from 'lucide-react';
import { formatExperienceDate, normalizePhone, validateExperience, validatePhone } from '../utils/profileValidation';

const steps = ['About you', 'Interests', 'Experience', 'Education', 'Skills & resume'];
const blankExperience = { company: '', title: '', startDate: '', endDate: '', current: false, location: '', description: '' };
const blankEducation = { institution: '', degree: '', fieldOfStudy: '', startYear: '', endYear: '', current: false };

export default function ApplicantOnboarding({ user, initialProfile, onComplete }) {
  const [step, setStep] = useState(0);
  const [saving, setSaving] = useState(false);
  const [error, setError] = useState('');
  const [phoneTouched, setPhoneTouched] = useState(false);
  const [experienceErrors, setExperienceErrors] = useState({});
  const [profile, setProfile] = useState({ phone: '', location: '', headline: '', summary: '', interests: [], preferredJobTitles: [], preferredWorkArrangements: [], preferredLocations: [], employmentTypes: [], skills: [], experiences: [], education: [], projects: [], certifications: [], achievements: [], resumeUrl: '', resumeFileName: '', ...(initialProfile || {}) });

  const update = (field, value) => setProfile((current) => ({ ...current, [field]: value }));
  const toggle = (field, value) => update(field, profile[field].includes(value) ? profile[field].filter((item) => item !== value) : [...profile[field], value]);
  const addText = (field, value) => { const next = value.trim(); if (next && !profile[field].includes(next)) update(field, [...profile[field], next]); };
  const updateItem = (field, index, key, value) => update(field, profile[field].map((item, itemIndex) => itemIndex === index ? { ...item, [key]: value } : item));
  const save = async () => {
    const phoneError = profile.phone ? validatePhone(profile.phone) : '';
    const nextExperienceErrors = Object.fromEntries(profile.experiences.map((experience, index) => [index, validateExperience(experience)]).filter(([, value]) => value));
    setPhoneTouched(true);
    setExperienceErrors(nextExperienceErrors);
    if (phoneError || Object.keys(nextExperienceErrors).length) {
      setError(phoneError || 'Fix the highlighted experience dates before saving.');
      return;
    }
    setSaving(true); setError('');
    try {
      const response = await axios.put('http://localhost:5001/api/applicant/profile', { ...profile, profileCompleted: true }, { headers: { Authorization: `Bearer ${localStorage.getItem('token')}` } });
      onComplete(response.data.profile);
    } catch (err) { setError(err.response?.data?.error || 'Profile could not be saved.'); } finally { setSaving(false); }
  };
  const canContinue = step !== 0 || (profile.headline.trim() && profile.location.trim());

  return <div className="app-shell flex min-h-screen items-center justify-center p-4 sm:p-8"><div className="w-full max-w-4xl rounded-[28px] border border-slate-200 bg-white shadow-soft">
    <div className="border-b border-slate-200 p-6 sm:p-8"><div className="mb-2 text-[11px] font-semibold uppercase tracking-[0.18em] text-indigo-500">Build your career profile</div><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><h1 className="text-3xl font-semibold tracking-[-0.05em] text-slate-900">Tell us what makes you a great hire.</h1><p className="mt-2 text-sm text-slate-500">Hi {user.name}. You can update these details anytime.</p></div><div className="text-sm font-medium text-slate-500">Step {step + 1} of {steps.length}</div></div><div className="mt-6 grid grid-cols-5 gap-2">{steps.map((label, index) => <div key={label} className={`h-1 rounded-full ${index <= step ? 'bg-indigo-600' : 'bg-slate-200'}`} aria-label={label} />)}</div></div>
    <div className="min-h-[390px] p-6 sm:p-8">{error && <div className="mb-5 rounded-xl border border-red-200 bg-red-50 px-3 py-2 text-sm text-red-700">{error}</div>}
      {step === 0 && <div className="grid gap-4 sm:grid-cols-2"><Field label="Full name" value={user.name} disabled /><Field label="Email" value={user.email} disabled /><Field label="Phone number" type="tel" inputMode="numeric" maxLength={10} value={profile.phone} onChange={(value) => update('phone', normalizePhone(value))} onBlur={() => setPhoneTouched(true)} placeholder="9876543210" error={phoneTouched && profile.phone ? validatePhone(profile.phone) : ''} /><Field label="Current location" value={profile.location} onChange={(value) => update('location', value)} placeholder="City, country" required /><div className="sm:col-span-2"><Field label="Professional headline" value={profile.headline} onChange={(value) => update('headline', value)} placeholder="Frontend Developer | React | JavaScript" required /></div><div className="sm:col-span-2"><label className="mb-1.5 block text-sm font-medium text-slate-700">Professional summary</label><textarea value={profile.summary} onChange={(event) => update('summary', event.target.value)} rows="4" className="w-full rounded-xl border border-slate-200 bg-slate-50 px-3.5 py-2.5 text-sm outline-none focus:border-indigo-300 focus:bg-white" placeholder="A short introduction about your experience and goals." /></div></div>}
      {step === 1 && <div className="space-y-6"><ChoiceGroup label="What kind of work are you looking for?" field="interests" values={['Frontend Development', 'Backend Development', 'Full Stack Development', 'Mobile Development', 'UI/UX Design', 'Data Science', 'DevOps', 'Cloud Engineering', 'Cybersecurity', 'Product Management']} profile={profile} toggle={toggle} /><ChoiceGroup label="Preferred work arrangement" field="preferredWorkArrangements" values={['Remote', 'Hybrid', 'On-site']} profile={profile} toggle={toggle} /><ChoiceGroup label="Employment type" field="employmentTypes" values={['Full-time', 'Part-time', 'Internship', 'Contract']} profile={profile} toggle={toggle} /><TagInput label="Preferred job titles" field="preferredJobTitles" profile={profile} addText={addText} placeholder="React Developer" /><TagInput label="Preferred locations" field="preferredLocations" profile={profile} addText={addText} placeholder="Mumbai" /></div>}
      {step === 2 && <RepeatableSection title="Experience" items={profile.experiences} field="experiences" blank={blankExperience} update={update} renderItem={(item, index) => <div className="grid gap-3 sm:grid-cols-2"><Field label="Company" value={item.company} onChange={(value) => updateItem('experiences', index, 'company', value)} /><Field label="Job title" value={item.title} onChange={(value) => updateItem('experiences', index, 'title', value)} /><DateField label="Start date" value={item.startDate} onChange={(value) => updateItem('experiences', index, 'startDate', formatExperienceDate(value))} onBlur={() => setExperienceErrors((current) => ({ ...current, [index]: validateExperience(item) }))} error={experienceErrors[index] && !item.current ? experienceErrors[index] : ''} /><DateField label="End date" value={item.current ? 'Present' : item.endDate} disabled={item.current} onChange={(value) => updateItem('experiences', index, 'endDate', formatExperienceDate(value))} onBlur={() => setExperienceErrors((current) => ({ ...current, [index]: validateExperience(item) }))} error={experienceErrors[index] && !item.current && item.endDate ? experienceErrors[index] : ''} placeholder="YYYYMM" /><label className="flex items-center gap-2 text-sm text-slate-600"><input type="checkbox" checked={item.current} onChange={(event) => { updateItem('experiences', index, 'current', event.target.checked); setExperienceErrors((current) => ({ ...current, [index]: '' })); }} /> Currently working here</label><div className="sm:col-span-2"><Field label="Description" value={item.description} onChange={(value) => updateItem('experiences', index, 'description', value)} /></div></div>} />}
      {step === 3 && <RepeatableSection title="Education" items={profile.education} field="education" blank={blankEducation} update={update} renderItem={(item, index) => <div className="grid gap-3 sm:grid-cols-2"><Field label="College or university" value={item.institution} onChange={(value) => updateItem('education', index, 'institution', value)} /><Field label="Degree" value={item.degree} onChange={(value) => updateItem('education', index, 'degree', value)} /><Field label="Field of study" value={item.fieldOfStudy} onChange={(value) => updateItem('education', index, 'fieldOfStudy', value)} /><Field label="Start year" value={item.startYear} onChange={(value) => updateItem('education', index, 'startYear', value)} /><Field label="End year" value={item.endYear} onChange={(value) => updateItem('education', index, 'endYear', value)} /><label className="flex items-center gap-2 text-sm text-slate-600"><input type="checkbox" checked={item.current} onChange={(event) => updateItem('education', index, 'current', event.target.checked)} /> Currently studying</label></div>} />}
      {step === 4 && <div className="space-y-6"><TagInput label="Skills" field="skills" profile={profile} addText={addText} placeholder="React" /><div className="rounded-2xl border border-slate-200 bg-slate-50 p-5"><div className="text-sm font-semibold text-slate-800">Resume reference</div><p className="mt-1 text-sm text-slate-500">Add a resume file reference now, or leave it empty and complete this later.</p><div className="mt-4 grid gap-3 sm:grid-cols-2"><Field label="Resume file name" value={profile.resumeFileName} onChange={(value) => update('resumeFileName', value)} placeholder="resume.pdf" /><Field label="Resume URL" value={profile.resumeUrl} onChange={(value) => update('resumeUrl', value)} placeholder="Secure file reference" /></div></div></div>}
    </div>
    <div className="flex items-center justify-between border-t border-slate-200 p-6 sm:p-8"><button type="button" disabled={step === 0 || saving} onClick={() => setStep((current) => current - 1)} className="inline-flex items-center gap-2 rounded-xl border border-slate-200 px-4 py-2.5 text-sm font-semibold text-slate-600 disabled:invisible"><ArrowLeft size={15} /> Back</button>{step < steps.length - 1 ? <button type="button" disabled={!canContinue || saving} onClick={() => setStep((current) => current + 1)} className="inline-flex items-center gap-2 rounded-xl bg-indigo-600 px-4 py-2.5 text-sm font-semibold text-white disabled:cursor-not-allowed disabled:bg-slate-300">Continue <ArrowRight size={15} /></button> : <button type="button" disabled={saving} onClick={save} className="inline-flex items-center gap-2 rounded-xl bg-indigo-600 px-4 py-2.5 text-sm font-semibold text-white disabled:bg-slate-300">{saving ? 'Saving...' : 'Complete profile'} <Check size={15} /></button>}</div>
  </div></div>;
}

function Field({ label, value, onChange, placeholder, disabled, required, error, onBlur, type = 'text', inputMode, maxLength }) { return <label className="block"><span className="mb-1.5 block text-sm font-medium text-slate-700">{label}{required && <span className="text-red-500"> *</span>}</span><input type={type} inputMode={inputMode} maxLength={maxLength} value={value || ''} onChange={(event) => onChange?.(event.target.value)} onBlur={onBlur} placeholder={placeholder} disabled={disabled} className={`w-full rounded-xl border bg-slate-50 px-3.5 py-2.5 text-sm outline-none focus:bg-white disabled:cursor-not-allowed disabled:bg-slate-100 disabled:text-slate-500 ${error ? 'border-red-300 focus:border-red-400' : 'border-slate-200 focus:border-indigo-300'}`} />{error && <span className="mt-1 block text-xs text-red-600">{error}</span>}</label>; }
function DateField({ label, value, onChange, placeholder, disabled, error, onBlur }) { return <Field label={label} value={value} onChange={onChange} onBlur={onBlur} placeholder={placeholder || 'YYYYMM'} disabled={disabled} error={error} inputMode="numeric" maxLength={7} />; }
function ChoiceGroup({ label, field, values, profile, toggle }) { return <div><div className="mb-2 text-sm font-medium text-slate-700">{label}</div><div className="flex flex-wrap gap-2">{values.map((value) => <button key={value} type="button" aria-pressed={profile[field].includes(value)} onClick={() => toggle(field, value)} className={`rounded-full border px-3 py-2 text-sm transition ${profile[field].includes(value) ? 'border-indigo-500 bg-indigo-50 text-indigo-700' : 'border-slate-200 bg-white text-slate-600 hover:border-indigo-200'}`}>{value}</button>)}</div></div>; }
function TagInput({ label, field, profile, addText, placeholder }) { const [value, setValue] = useState(''); return <div><label className="mb-1.5 block text-sm font-medium text-slate-700">{label}</label><div className="flex gap-2"><input value={value} onChange={(event) => setValue(event.target.value)} onKeyDown={(event) => { if (event.key === 'Enter') { event.preventDefault(); addText(field, value); setValue(''); } }} placeholder={placeholder} className="min-w-0 flex-1 rounded-xl border border-slate-200 bg-slate-50 px-3.5 py-2.5 text-sm outline-none focus:border-indigo-300 focus:bg-white" /><button type="button" onClick={() => { addText(field, value); setValue(''); }} className="inline-flex items-center gap-1 rounded-xl border border-slate-200 px-3 py-2 text-sm font-semibold text-slate-600"><Plus size={15} /> Add</button></div><div className="mt-2 flex flex-wrap gap-2">{profile[field].map((item) => <span key={item} className="rounded-full bg-slate-100 px-3 py-1.5 text-xs font-medium text-slate-600">{item}</span>)}</div></div>; }
function RepeatableSection({ title, items, field, blank, update, renderItem }) { return <div><div className="mb-4 flex items-center justify-between"><div><h2 className="text-lg font-semibold text-slate-900">{title}</h2><p className="mt-1 text-sm text-slate-500">Add as many entries as apply to you.</p></div><button type="button" onClick={() => update(field, [...items, { ...blank }])} className="inline-flex items-center gap-1 rounded-xl border border-slate-200 px-3 py-2 text-sm font-semibold text-slate-600"><Plus size={15} /> Add {title.toLowerCase()}</button></div>{items.length === 0 ? <div className="rounded-2xl border border-dashed border-slate-200 bg-slate-50 p-10 text-center text-sm text-slate-500">No {title.toLowerCase()} added yet. You can continue without one.</div> : <div className="space-y-4">{items.map((item, index) => <div key={item._id || index} className="rounded-2xl border border-slate-200 p-4"><div className="mb-4 flex justify-end"><button type="button" onClick={() => update(field, items.filter((_, itemIndex) => itemIndex !== index))} aria-label={`Remove ${title.toLowerCase()}`} className="text-slate-400 hover:text-red-600"><Trash2 size={16} /></button></div>{renderItem(item, index)}</div>)}</div>}</div>; }